feat: Enhanced script functionality, refactored structure, and improved theme handling
    feat: Argument parsing - The script now supports command-line arguments for specifying the themes directory and theme symbolic link's directory.
    	Additionally, it provides a help message to assist users in understanding available options.
    feat: Theme preservation - Prior to applying a new theme, the script creates a backup of the current theme. If no theme is selected or the user exits early, the original theme is restored.
    feat: Ctrl+C handling - Implemented signal handling for Ctrl+C to gracefully perform cleanup operations and maintain the original theme before terminating the script.
    feat: Automatic themes repository cloning - If no themes are found or the themes directory does not exist, the script automatically clones the themes repository from the URL in env_vars file.

Refactor:

    Improved code structure and modularity.

CI: Introduced env_vars file - Added an env_vars file to store environment variables.
"

diff --git a/kitty_theme_switcher b/kitty_theme_switcher
--- a/kitty_theme_switcher
+++ b/kitty_theme_switcher
@@ -1,27 +1,67 @@
-#! /bin/sh
+#!/bin/sh
 
-KITTY=$XDG_CONFIG_HOME/kitty
-THEMES=$XDG_CONFIG_HOME/kitty/kitty-themes/themes
-LINK=$XDG_CONFIG_HOME/kitty/kitty.conf
+VARS="./env_vars"
+source "$VARS"
+UTILS="./utilities"
+source "$UTILS"
+export $(cut -d= -f1 "$VARS")
 
-choose_theme() {
-  THEME=$(ls $THEMES | fzf)
-  if [ -h "$LINK" ]; then
-    rm -f $LINK
-  fi
-  ln -s "$THEMES/$THEME" "$LINK"
-  xdotool keydown ctrl shift F5
-  xdotool keyup F5 shift ctrl
+display_help() {
+  echo "Usage: $0 [-h|--help] [-d|--themes-dir <dir>] [-t|--theme-dir <dir>]"
+  echo "Choose and apply a theme for the kitty terminal emulator."
+  echo "Options:"
+  echo "  -h, --help               Display this help message."
+  echo "  -d, --themes-dir <dir>   Set the directory where kitty themes are stored. Default is: $THEMES_DIR"
+  echo "  -t, --theme-dir <dir>    Set the directory where the current kitty theme link is created. Default is: $THEME_PATH"
+}
+check_args() {
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+
+    case $key in
+      -h|--help)
+        display_help
+        exit 0
+        ;;
+      -d|--themes-dir)
+        THEMES_DIR="$2"
+        shift
+        ;;
+      -t|--theme-dir)
+        THEME_PATH="$2"
+        shift
+        ;;
+      *)
+        echo "Invalid option: $key"
+        display_help
+        exit 1
+        ;;
+    esac
+    shift
+  done
 }
 
-if [ -d "$THEMES" ]; then
-  choose_theme
-else
-  echo "$THEMES don't exist"
-  if [ ! -d "$KITTY" ]; then
-    mkdir -p $KITTY
+run() {
+  check_args "$@"
+  if [ -z "$(ls -A "$THEMES_DIR")" ] || [ ! -d "$THEMES_DIR" ]; then
+    echo "No Themes found"
+    echo "Cloning from $THEMES_REPO"
+    rm -rf "$THEMES_DIR" 2>/dev/null
+    clone_themes_from_git
   fi
-  echo "Cloning kitty themes"
-  git clone --depth 1 https://github.com/dexpota/kitty-themes.git ~/.config/kitty/kitty-themes
-  choose_theme
-fi
+  create_backup
+  THEME=$(choose_theme)
+  if [ "$THEME" = "empty" ]; then
+    exiting
+  elif [ -n "$THEME" ]; then
+    apply_theme
+
+  else
+    undo_changes
+  fi
+  refresh_kitty
+}
+
+run "$@"
+unset_variables_from_file "$VARS"
+
